name: Code style
on: pull_request
jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "laravel-pint"
      - run:  .\vendor\bin\php-cs-fixer fix --config=phpCsFixerConfig.php  --dry-run --diff


