name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write    

jobs:
  PHP-Unit:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        configuration: phpunit.xml.dist
        php_extensions: gettext xdebug
        args: --coverage-clover ./coverage.xml --testdox
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml

